// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjnwAavVt4bfBZYxdAveD2HuMDiCmJY4Q',
    appId: '1:612781804475:web:9dd3ff9ce8c8c48912529e',
    messagingSenderId: '612781804475',
    projectId: 'promofy-765c0',
    authDomain: 'promofy-765c0.firebaseapp.com',
    storageBucket: 'promofy-765c0.firebasestorage.app',
    measurementId: 'G-3RKWPGT2D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWKXaJyBNS9NWkFbVeCc752ug4DQDfUOc',
    appId: '1:612781804475:android:bd5da3c569c695ec12529e',
    messagingSenderId: '612781804475',
    projectId: 'promofy-765c0',
    storageBucket: 'promofy-765c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLsq3ACPy3kcPPWIfaoPMyli6GkRD0Sk',
    appId: '1:612781804475:ios:d567c8aa1f0b0edf12529e',
    messagingSenderId: '612781804475',
    projectId: 'promofy-765c0',
    storageBucket: 'promofy-765c0.firebasestorage.app',
    iosBundleId: 'com.promofy.app',
  );

}